/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.grapher.gui;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import org.grapher.sys.AudioAnalizer;
import static org.grapher.sys.SysInfo.BUFF_SIZE;
import static org.grapher.sys.SysInfo.GRAPH_HEIGHT;

/**
 *
 * @author martin
 */
public class FormAnalizer extends javax.swing.JFrame {

    private AudioAnalizer analizer;
    
    public FormAnalizer() throws LineUnavailableException {
        initComponents();
        configPanel();
        analizer = new AudioAnalizer(audioPanel);
        Thread.currentThread().setPriority(Thread.MAX_PRIORITY);
        setSize(1366, 768);
        setLocationRelativeTo(null);
    }
    
    private void configPanel(){
        GridLayout layout = new GridLayout(GRAPH_HEIGHT, BUFF_SIZE);
        audioPanel.setLayout(layout);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioPanel = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout audioPanelLayout = new javax.swing.GroupLayout(audioPanel);
        audioPanel.setLayout(audioPanelLayout);
        audioPanelLayout.setHorizontalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        audioPanelLayout.setVerticalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        getContentPane().add(audioPanel, java.awt.BorderLayout.CENTER);

        btnStart.setText("Comenzar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        analizer.start();
        btnStart.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FormAnalizer().setVisible(true);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(FormAnalizer.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel audioPanel;
    private javax.swing.JButton btnStart;
    // End of variables declaration//GEN-END:variables
}
